(deftheme solarized
  "Created 2017-10-11.")

(defface solarized-base0-bg
  '((((background dark) (class color) (min-colors 88)) (:background "#002b36"))
    (((background light) (class color) (min-colors 88)) (:background "#fdf6e3"))
    (((background dark)) (:background "brightblack"))
    (t (:background "brightwhite")))
  "Darkest/lightest background tone")
(defface solarized-base1-bg
  '((((background dark) (class color) (min-colors 88)) (:background "#073642"))
    (((background light) (class color) (min-colors 88)) (:background "#eee8d5"))
    (((background dark)) (:background "black"))
    (t (:background "white")))
  "Least contrasting background tone")
(defface solarized-base2-fg
  '((((background dark) (class color) (min-colors 88)) (:foreground "#586e75"))
    (((background light) (class color) (min-colors 88)) (:foreground "#93a1a1"))
    (((background dark)) (:foreground "brightgreen"))
    (t (:foreground "brightcyan")))
  "Least contrasting content tone")

(custom-theme-set-faces
 'solarized
 '(button ((t (:inherit link))))
 '(cursor ((t (:background "#002b36"))))
 '(custom-variable-tag ((t (:foreground "#268bd2" :weight bold))))
 '(escape-glyph ((t (:foreground "#859900"))))
 '(fixed-pitch ((t (:family "monospace"))))
 '(font-lock-builtin-face ((t (:foreground "#b58900"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#93a1a1"))))
 '(font-lock-constant-face ((t (:foreground "#6c71c4"))))
 '(font-lock-doc-face ((t (:foreground "#93a1a1"))))
 '(font-lock-function-name-face ((t (:foreground "#d33682"))))
 '(font-lock-keyword-face ((t (:weight bold))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:foreground "#dc322f"))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#268bd2"))))
 '(font-lock-type-face ((t (:slant italic))))
 '(font-lock-variable-name-face ((t (:foreground "#b58900"))))
 '(font-lock-warning-face ((t (:foreground "#dc322f" :weight bold))))
 '(fringe ((t (:background "#eee8d5" :foreground "#586e75"))))
 '(header-line ((t (:inherit mode-line))))
 '(helm-M-x-key ((t (:inherit link))))
 '(helm-buffer-not-saved ((t (:foreground "#dc322f"))))
 '(helm-buffer-process ((t (:foreground "#cb4b16"))))
 '(helm-candidate-number ((t (:weight bold))))
 '(helm-match ((t (:foreground "#dc322f"))))
 '(helm-prefarg ((t (:foreground "#dc322f"))))
 '(helm-selection ((t (:background "#d33682" :foreground "White"))))
 '(helm-source-header ((t (:background "#eee8d5" :foreground "#b58900" :height 1.3))))
 '(highlight ((t (:background "#eee8d5"))))
 '(isearch ((t (:background "#d33682" :foreground "White"))))
 '(isearch-fail ((t (:background "#d33682" :foreground "White"))))
 '(lazy-highlight ((t (:background "#93a1a1" :foreground "White"))))
 '(link ((t (:foreground "#b58900" :underline t))))
 '(link-visited ((t (:inherit link :foreground "#859900"))))
 '(linum ((t (:inherit (solarized-base1-bg solarized-base2-fg)))))
 '(match ((t (:background "#2aa198" :foreground "White"))))
 '(minibuffer-prompt ((t (:foreground "#268bd2"))))
 '(mode-line ((t (:background "#eee8d5" :box (:line-width 1 :color "#93a1a1")))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:underline t))))
 '(mode-line-inactive ((t (:inherit mode-line :background "#fdf6e3"))))
 '(neo-dir-link-face ((t (:foreground "#268bd2"))))
 '(neo-file-link-face ((t nil)))
 '(neo-header-face ((t (:foreground "#b58900"))))
 '(neo-root-dir-face ((t (:foreground "#d33682"))))
 '(next-error ((t (:inherit (region)))))
 '(org-agenda-date ((t (:weight bold))))
 '(org-agenda-date-today ((t (:inherit org-agenda-date :slant italic))))
 '(org-agenda-done ((t (:foreground "#839496"))))
 '(org-agenda-structure ((t (:foreground "#b58900"))))
 '(org-code ((t (:background "#eee8d5" :family "monospace"))))
 '(org-date ((t (:foreground "#268bd2" :underline t))))
 '(org-date-selected ((t (:background "#dc322f" :foreground "White"))))
 '(org-done ((t (:foreground "#2aa198" :weight bold))))
 '(org-priority ((t (:inherit org-todo))))
 '(org-property-value ((t (:foreground "#268bd2"))))
 '(org-scheduled ((t nil)))
 '(org-scheduled-previously ((t (:foreground "#dc322f"))))
 '(org-scheduled-today ((t nil)))
 '(org-special-keyword ((t (:foreground "#6c71c4"))))
 '(org-tag ((t (:foreground "#6c71c4" :weight bold))))
 '(org-todo ((t (:foreground "#d33682" :weight bold))))
 '(outline-1 ((t (:foreground "#b58900" :underline "#657b83" :height 1.6))))
 '(outline-2 ((t (:weight bold))))
 '(outline-3 ((t (:inherit outline-2))))
 '(outline-4 ((t (:inherit outline-3))))
 '(outline-5 ((t (:inherit outline-4))))
 '(outline-6 ((t (:inherit outline-5))))
 '(query-replace ((t (:inherit (isearch)))))
 '(region ((t (:background "#d33682" :foreground "White"))))
 '(secondary-selection ((t (:background "#268bd2" :foreground "White"))))
 '(sh-quoted-exec ((default (:inherit (font-lock-function-name-face)))))
 '(shadow ((t (:foreground "#839496"))))
 '(tooltip ((t (:background "#eee8d5" :foreground "#586e75"))))
 '(trailing-whitespace ((t (:background "#dc322f" :foreground "White"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(warning ((t (:foreground "#dc322f" :weight bold))))
 '(whitespace-indentation ((t (:inherit whitespace-line))))
 '(whitespace-line ((t (:inherit highlight))))
 '(whitespace-newline ((t (:inherit whitespace-space))))
 '(whitespace-space ((t (:inherit font-lock-comment-face))))
 '(whitespace-space-after-tab ((t (:inherit whitespace-line))))
 '(whitespace-space-before-tab ((t (:inherit whitespace-line))))
 '(whitespace-trailing ((t (:inherit font-lock-warning-face))))
 '(default ((((background dark) (class color) (min-colors 88)) (:background "#002b36" :foreground "#839496" :inherit nil :stipple nil :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 140 :width normal :foundry "nil" :family "Roboto Mono for Powerline"))
            (((background light) (class color) (min-colors 88)) (:background "#fdf6e3" :foreground "#657b83" :inherit nil :stipple nil :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 140 :width normal :foundry "nil" :family "Roboto Mono for Powerline"))
            (((background dark)) (:background "brightblack" :foreground "brightblue" :inherit nil :stipple nil :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 140 :width normal :foundry "nil" :family "Roboto Mono for Powerline"))
            (t (:background "brightwhite" :foreground "brightyellow" :inherit nil :stipple nil :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 140 :width normal :foundry "nil" :family "Roboto Mono for Powerline")))))

(provide-theme 'solarized)
