(deftheme solarized-light
  "Solarized Light Theme")

(custom-theme-set-faces
 'solarized-light
 '(cursor ((t (:background "#002b36"))))
 '(fixed-pitch ((t (:family "monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#859900"))))
 '(minibuffer-prompt ((t (:foreground "#268bd2"))))
 '(highlight ((t (:background "#eee8d5"))))
 '(region ((t (:background "#d33682" :foreground "White"))))
 '(shadow ((t (:foreground "#839496"))))
 '(secondary-selection ((t (:background "#268bd2" :foreground "White"))))
 '(trailing-whitespace ((t (:background "#dc322f" :foreground "White"))))
 '(font-lock-builtin-face ((t (:foreground "#b58900"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#93a1a1"))))
 '(font-lock-constant-face ((t (:foreground "#6c71c4"))))
 '(font-lock-doc-face ((t (:foreground "#93a1a1"))))
 '(font-lock-function-name-face ((t (:foreground "#d33682"))))
 '(font-lock-keyword-face ((t (:weight bold))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:foreground "#dc322f"))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#268bd2"))))
 '(font-lock-type-face ((t (:slant italic))))
 '(font-lock-variable-name-face ((t (:foreground "#b58900"))))
 '(font-lock-warning-face ((t (:foreground "#dc322f" :weight bold))))
 '(button ((t (:inherit link))))
 '(link ((t (:foreground "#b58900" :underline t))))
 '(link-visited ((t (:inherit link :foreground "#859900"))))
 '(fringe ((t (:background "#eee8d5" :foreground "#586e75"))))
 '(header-line ((t (:inherit mode-line))))
 '(tooltip ((t (:background "#eee8d5" :foreground "#586e75"))))
 '(mode-line ((t (:background "#eee8d5" :box (:line-width 1 :color "#93a1a1")))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:underline t))))
 '(mode-line-inactive ((t (:inherit mode-line :background "#fdf6e3"))))
 '(isearch ((t (:background "#d33682" :foreground "White"))))
 '(isearch-fail ((t (:background "#d33682" :foreground "White"))))
 '(lazy-highlight ((t (:background "#93a1a1" :foreground "White"))))
 '(match ((t (:background "#2aa198" :foreground "White"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(org-todo ((t (:foreground "#d33682" :weight bold))))
 '(outline-1 ((t (:foreground "#b58900" :underline "#657b83" :height 1.6))))
 '(outline-2 ((t (:weight bold))))
 '(outline-3 ((t (:inherit outline-2))))
 '(outline-4 ((t (:inherit outline-3))))
 '(outline-5 ((t (:inherit outline-4))))
 '(outline-6 ((t (:inherit outline-5))))
 '(org-special-keyword ((t (:foreground "#6c71c4"))))
 '(org-property-value ((t (:foreground "#268bd2"))))
 '(org-done ((t (:foreground "#2aa198" :weight bold))))
 '(org-date ((t (:foreground "#268bd2" :underline t))))
 '(helm-selection ((t (:background "#d33682" :foreground "White"))))
 '(helm-source-header ((t (:background "#eee8d5" :foreground "#b58900" :height 1.3))))
 '(helm-candidate-number ((t (:weight bold))))
 '(helm-match ((t (:foreground "#dc322f"))))
 '(org-date-selected ((t (:background "#dc322f" :foreground "White"))))
 '(org-tag ((t (:foreground "#6c71c4" :weight bold))))
 '(org-agenda-structure ((t (:foreground "#b58900"))))
 '(warning ((t (:foreground "#dc322f" :weight bold))))
 '(org-agenda-date-today ((t (:inherit org-agenda-date :slant italic))))
 '(org-agenda-date ((t (:weight bold))))
 '(org-scheduled ((t nil)))
 '(org-scheduled-today ((t nil)))
 '(org-scheduled-previously ((t (:foreground "#dc322f"))))
 '(org-agenda-done ((t (:foreground "#839496"))))
 '(neo-root-dir-face ((t (:foreground "#d33682"))))
 '(neo-dir-link-face ((t (:foreground "#268bd2"))))
 '(neo-file-link-face ((t nil)))
 '(custom-variable-tag ((t (:foreground "#268bd2" :weight bold))))
 '(neo-header-face ((t (:foreground "#b58900"))))
 '(default ((t (:inherit nil :stipple nil :background "#fdf6e3" :foreground "#657b83" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 140 :width normal :foundry "nil" :family "Roboto Mono for Powerline")))))

(provide-theme 'solarized-light)
