#!/usr/bin/env bash

PATH="$(pwd)/home/bin:$PATH"

disto=$(x-distro-name)
x-info "distro detected: $disto"
if [[ $disto != "elementary" && $disto != "fedora" ]]; then
	x-error "distro unsupported"
	exit 1
fi

x-cmd "mkdir -p $HOME/.gsettings.backup"
x-cmd "gsettings list-recursively | sort > $HOME/.gsettings.backup/$(date --iso-8601=ns).txt"

x-update

x-backup-file $HOME/.bash_profile
x-backup-file $HOME/.bashrc

x-install curl
x-install emacs
x-install fortune-mod
x-install gcc
x-install gnome-disk-utility
x-install gnome-system-monitor
x-install gnome-terminal
x-install make
x-install ncurses-term
x-install neofetch
x-install rsync
x-install stow
x-install tmux
x-install tree
x-install vim

x-cmd "stow -v -t ~ home"

x-cmd "vim +PlugInstall +qall"

. bin/$disto
. bin/gnome-terminal
. bin/gnome
