#!/bin/bash

source home/bin/include

##############################
# Backup Configuration
##############################

cmd "mkdir -p $HOME/.gsettings.backup"
cmd "gsettings list-recursively | sort > $HOME/.gsettings.backup/$(date --iso-8601=ns).txt"

##############################
# Install
##############################

update

backup $HOME/.bash_profile
backup $HOME/.bashrc

install curl
install emacs
install fortune-mod
install gcc
install gnome-disk-utility
install gnome-system-monitor
install gnome-terminal
install make
install neofetch
install rsync
install stow
install tmux
install tree
install vim

cmd "stow -v -t ~ home"

cmd "vim +PlugInstall +qall"

source bin/$OS_NAME

source bin/gnome-terminal
source bin/gnome
