(global-set-key (kbd "M-x") 'helm-M-x)
(global-set-key (kbd "C-x C-b") 'helm-buffers-list)

(defun leader-bind (sequence action)
  (global-set-key (kbd (concat "C-c " sequence)) action))

(leader-bind "b b" 'helm-buffers-list)
(leader-bind "b c" 'kill-this-buffer)
(leader-bind "b k" 'kill-buffer)
(leader-bind "b l" 'list-buffers)
(leader-bind "b o" 'kill-other-buffers)
(leader-bind "b s" 'save-buffer)
(leader-bind "b w" 'read-only-mode)
(leader-bind "c" 'helm-project-list)
(leader-bind "e c" 'save-buffers-kill-terminal)
(leader-bind "f c" 'copy-file)
(leader-bind "f d" 'delete-current-buffer-file)
(leader-bind "f f" 'helm-projectile-find-file)
(leader-bind "f m" 'rename-current-buffer-file)
(leader-bind "f r" 'helm-projectile-recentf)
(leader-bind "j d" 'find-function)
(leader-bind "j i" 'open-init-el)
(leader-bind "j k" 'open-keys-el)
(leader-bind "m m" 'helm-mark-ring)
(leader-bind "q q" 'helm-execute-kmacro)
(leader-bind "s a" 'helm-projectile-ack)
(leader-bind "y y" 'helm-show-kill-ring)

