#!/usr/bin/osascript
# move-active-window-top
#
# Move the active window to the top of the screen.

set windowLib to (load script file "::helpers:window.scpt")

tell windowLib
	set deskBnds to getDesktopBounds()

	set wnd to getActiveWindow()
	set wndBnds to getWindowBounds(wnd)
	
	set vec to getVector(getBoundsTopLeft(wndBnds), getBoundsTopLeft(deskBnds))
	set bnds to getBoundsTranslation(wndBnds, {0, item 2 of vec})

	setWindowBounds(wnd, bnds)
end tell
