#!/usr/bin/osascript
# move-active-window-bottom-left
#
# Move the active window to the bottom left of the screen.

set windowLib to (load script file "::helpers:window.scpt")

tell windowLib
	set deskBnds to getDesktopBounds()

	set wnd to getActiveWindow()
	set wndBnds to getWindowBounds(wnd)
	
	set vec to getVector(getBoundsBottomLeft(wndBnds), getBoundsBottomLeft(deskBnds))
	set bnds to getBoundsTranslation(wndBnds, vec)

	setWindowBounds(wnd, bnds)
end tell
