#!/usr/bin/osascript
# move-active-window-bottom-right
#
# Move the active window to the bottom right of the screen.

set windowLib to (load script file "::helpers:window.scpt")

tell windowLib
	set deskBnds to getDesktopBounds()

	set wnd to getActiveWindow()
	set wndBnds to getWindowBounds(wnd)
	
	set vec to getVector(getBoundsBottomRight(wndBnds), getBoundsBottomRight(deskBnds))
	set bnds to getBoundsTranslation(wndBnds, vec)

	setWindowBounds(wnd, bnds)
end tell
