#!/usr/bin/osascript
# move-active-window-left
#
# Move the active window to the left side of the screen.

set windowLib to (load script file "::helpers:window.scpt")

tell windowLib
	set deskBnds to getDesktopBounds()

	set wnd to getActiveWindow()
	set wndBnds to getWindowBounds(wnd)
	
	set vec to getVector(getBoundsTopLeft(wndBnds), getBoundsTopLeft(deskBnds))
	set bnds to getBoundsTranslation(wndBnds, {item 1 of vec, 0})

	setWindowBounds(wnd, bnds)
end tell
