#!/usr/bin/env bash
if [ $# -eq "1" ]
then
	DATE=$(TZ=${1} date +"%A %B %-d • %-I:%M %p %Z")
else
	DATE=$(date +"%A %B %-d • %-I:%M %p %Z")
fi
osascript -e "tell application \"Alfred 3\" to run trigger \"Large Type\" in workflow \"trigger-large-type\" with argument \"${DATE}\""
