#!/usr/bin/env bash

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

alias ag="ag --hidden"
alias emacs='TERM=xterm-16color emacs --no-window-system'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias open='gio open 2>/dev/null'
alias ranger='ranger --choosedir=$HOME/.rangerdir; cd `cat $HOME/.rangerdir`; rm $HOME/.rangerdir'
alias trash='gio trash'
alias wttr='clear && curl wttr.in'
