#!/usr/bin/env bash

. s-solarized

function git_color {
	local git_status="$(git status 2> /dev/null)"
	if [[ ! $git_status =~ "working tree clean" ]]; then
		yellow
	elif [[ $git_status =~ "branch is ahead of" ]]; then
		cyan
	else
		base1
	fi
}

function git_branch {
	local git_status="$(git status 2> /dev/null)"
	local on_branch="On branch ([^${IFS}]*)"
	local on_commit="HEAD detached at ([^${IFS}]*)"
	if [[ $git_status =~ $on_branch ]]; then
		local branch=${BASH_REMATCH[1]}
		echo " $(git_color)$branch"
	elif [[ $git_status =~ $on_commit ]]; then
		local commit=${BASH_REMATCH[1]}
		echo " $(git_color)$commit"
	fi
}

PS1='$(bold)$(green)\u$(git_branch) $(blue)\w$(clr) \$ '
